USE [master]
GO

CREATE DATABASE [PassApp]
ON PRIMARY 
(
    NAME = N'PassApp',
    FILENAME = N'PassApp.mdf',
    SIZE = 8192KB,
    MAXSIZE = UNLIMITED,
    FILEGROWTH = 65536KB
)
LOG ON 
(
    NAME = N'PassApp_log',
    FILENAME = N'PassApp_log.ldf',
    SIZE = 8192KB,
    MAXSIZE = 2048GB,
    FILEGROWTH = 65536KB
);
GO

-- Enable Full-Text Search if the service is installed
IF (FULLTEXTSERVICEPROPERTY('IsFullTextInstalled') = 1)
BEGIN
    EXEC [PassApp].[dbo].[sp_fulltext_database] @action = 'enable';
END
GO
ALTER DATABASE [PassApp] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PassApp] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PassApp] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PassApp] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PassApp] SET ARITHABORT OFF 
GO
ALTER DATABASE [PassApp] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PassApp] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PassApp] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PassApp] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PassApp] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PassApp] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PassApp] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PassApp] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PassApp] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PassApp] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PassApp] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PassApp] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PassApp] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PassApp] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PassApp] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PassApp] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PassApp] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PassApp] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PassApp] SET  MULTI_USER 
GO
ALTER DATABASE [PassApp] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PassApp] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PassApp] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PassApp] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PassApp] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PassApp] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [PassApp] SET QUERY_STORE = OFF
GO
USE [PassApp]
GO
/****** Object:  Table [dbo].[CheckInLog]    Script Date: 10/15/2024 3:19:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CheckInLog](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DiscordId] [varchar](50) NOT NULL,
	[LastCheckIn] [datetime] NOT NULL,
	[DiscordUsername] [varchar](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[log]    Script Date: 10/15/2024 3:19:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[log](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DiscordId] [varchar](50) NOT NULL,
	[DiscordUsername] [varchar](100) NOT NULL,
	[Command] [varchar](100) NOT NULL,
	[Message] [text] NOT NULL,
	[DateTime] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserPoints]    Script Date: 10/15/2024 3:19:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserPoints](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DiscordId] [varchar](50) NOT NULL,
	[DiscordUsername] [varchar](100) NOT NULL,
	[Points] [int] NOT NULL,
	[LastUpdated] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserPointsTableLog]    Script Date: 10/15/2024 3:19:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserPointsTableLog](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DiscordId] [varchar](50) NOT NULL,
	[DiscordUsername] [varchar](100) NOT NULL,
	[AssignerId] [varchar](50) NOT NULL,
	[AssignerUsername] [varchar](100) NOT NULL,
	[Points] [int] NOT NULL,
	[InsertedAt] [datetime] NOT NULL,
	[RemovedAt] [datetime] NULL,
	[RemovedBy] [varchar](50) NULL,
	[Message] [nvarchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserProfile]    Script Date: 10/15/2024 3:19:55 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserProfile](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DiscordId] [varchar](50) NOT NULL,
	[DiscordUsername] [varchar](100) NOT NULL,
	[Email] [varchar](255) NULL,
	[WalletAddress] [varchar](255) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[log] ADD  DEFAULT (getdate()) FOR [DateTime]
GO
ALTER TABLE [dbo].[UserPoints] ADD  DEFAULT ((0)) FOR [Points]
GO
ALTER TABLE [dbo].[UserPoints] ADD  DEFAULT (getutcdate()) FOR [LastUpdated]
GO
ALTER TABLE [dbo].[UserPointsTableLog] ADD  DEFAULT (getutcdate()) FOR [InsertedAt]
GO
USE [master]
GO
ALTER DATABASE [PassApp] SET  READ_WRITE 
GO

CREATE TABLE [dbo].[Item](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](255) NOT NULL,
	[CreatedOn] [datetime] NOT NULL,
	[CreatedBy] [nvarchar](100) NOT NULL,
	[Cost] [bigint] NOT NULL,
	[ExpiresOn] [datetime] NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Item] ADD  DEFAULT (getutcdate()) FOR [CreatedOn]
GO

CREATE TABLE [dbo].[Redemption](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[ItemId] [int] NOT NULL,
	[DiscordId] [nvarchar](100) NOT NULL,
	[DiscordUsername] [nvarchar](255) NOT NULL,
	[ClaimedOn] [datetime] NOT NULL,
	[SentBy] [nvarchar](100) NULL,
	[SentOn] [datetime] NULL,
	[Spent] [bigint] NOT NULL,
	[RedemptionId] [nvarchar](21) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Redemption] ADD  DEFAULT (getdate()) FOR [ClaimedOn]
GO

ALTER TABLE [dbo].[Redemption]  WITH CHECK ADD FOREIGN KEY([ItemId])
REFERENCES [dbo].[Item] ([Id])
GO